version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fsts@2025
      MYSQL_DATABASE: app_data
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_container
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: fsts@2025
      MYSQL_DATABASE: app_data
    depends_on:
      - mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
